### ISSUE TITLE
请问运行爬虫代码的python和scrapy环境是哪个版本的

### ISSUE THREAD

**Issue by XiaoFuOS** [iphysresearch/TOP250movie_douban#6]
rt

**Comment by Jinchess** [comment]
python3.几版本吧，scrapy感觉都行，我猜的，好久用过的了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月21日(星期六) 晚上11:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [iphysresearch/TOP250movie_douban] 请问运行爬虫代码的python和scrapy环境是哪个版本的 (Issue #6)





 
Closed #6 as completed.
 
&mdash;
